version: 0.2

phases:
  install:
    commands:
      - powershell -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      # - choco install -y yarn
      - dir "C:\Program Files (x86)\"
      - choco install -y googlechrome
      - dir "C:\Program Files (x86)\Google\"
      - choco install -y opera
      - dir "C:\Program Files (x86)\"
      # - $env:Path += ";C:\Program Files (x86)\Yarn\bin\"
      # - echo $env:Path
      # - $Env:PATH += ";C:\Program Files (x86)\Yarn\bin\"
      # - echo $Env:PATH
      # - dir "C:\Program Files (x86)\Yarn\bin\"
      # - '"C:\Program Files (x86)\Yarn\bin\yarn"'
      # - node -v
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install --silent
  build:
    commands:
      # - yarn run lint
      - yarn run test.unit
      - yarn run build.prod --silent
      - $CODEBUILD_SRC_DIR_moab\moab-bin.exe makezip
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makeappx.exe"'
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makepri.exe"'

artifacts:
  files:
    - build/**/*
  discard-paths: yes