version: 0.2

phases:
  install:
    commands:
      - powershell -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      - choco install -y yarn
      - powershell -ExecutionPolicy unrestricted -Command "refreshenv"
      - dir "C:\Program Files (x86)\Yarn\bin\"
      - refreshenv
      - echo $Env:PATH
      # - powershell -ExecutionPolicy unrestricted -Command "yarn -v"
      - "C:\Program Files (x86)\Yarn\bin\yarn" -v
      - node -v
  pre_build:
    commands:
      - "C:\Program Files (x86)\Yarn\bin\yarn" install
  build:
    commands:
      - "C:\Program Files (x86)\Yarn\bin\yarn" run lint
      - "C:\Program Files (x86)\Yarn\bin\yarn" run test.unit
      - "C:\Program Files (x86)\Yarn\bin\yarn" run build.prod
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makeappx.exe"'
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makepri.exe"'
