version: 0.2

phases:
  install:
    commands:
      - powershell -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      # - choco install -y yarn
      - choco install --confirm --limit-output --no-progress googlechrome opera windows-sdk-10.1
      - dir "C:\Program Files (x86)\Windows Kits\10\bin\arm\"
      - dir "C:\Program Files (x86)\Windows Kits\10\bin\arm64\"
      - dir "C:\Program Files (x86)\Windows Kits\10\bin\x64\"
      - dir "C:\Program Files (x86)\Windows Kits\10\bin\x64\ucrt\"
      - dir "C:\Program Files (x86)\Windows Kits\10\bin\x86\"
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install --silent
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '[projects]'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '  [projects.ghostery-extension]'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '    edge_makepri_path = "C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64\\makepri.exe"'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '    edge_makeappx_path = "C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64\\makeappx.exe"'
      - type C:\Users\ContainerAdministrator\.moabconfig
  build:
    commands:
      # - yarn run lint
      - yarn run test.unit --verbose=false
      - yarn run build.prod --silent
      - '& "$env:CODEBUILD_SRC_DIR_moab\moab-bin.exe" build'

artifacts:
  files:
    - build/**/*
  discard-paths: yes