version: 0.2

phases:
  install:
    commands:
      - powershell -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      - choco install -y yarn
      - powershell -ExecutionPolicy unrestricted -Command "refreshenv"
      - dir "C:\Program Files (x86)\Yarn\bin\"
      - set PATH=$Env:PATH;"C:\Program Files (x86)\Yarn\bin\yarn"
      - refreshenv
      - echo $Env:PATH
      - yarn -v
      - node -v
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run lint
      - yarn run test.unit
      - yarn run build.prod
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makeappx.exe"'
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makepri.exe"'
