version: 0.2

env:
  variables:
    YARN_BIN: 'C:\Program Files (x86)\Yarn\bin\yarn.cmd'
    MOABCONFIG_PATH: 'C:\Users\ContainerAdministrator\.moabconfig'
    WINDOWS_SDK_VERSION: '10.0.18362.0'

phases:
  install:
    commands:
      - choco install --confirm --limit-output --no-progress --ignore-checksums git nodejs yarn googlechrome opera
      - choco install windows-sdk-10.1 --version $env:WINDOWS_SDK_VERSION --confirm --limit-output --no-progress --ignore-checksums
      - Add-Content -Path $env:MOABCONFIG_PATH -Value '[projects]'
      - Add-Content -Path $env:MOABCONFIG_PATH -Value '  [projects.ghostery-extension]'
      - Add-Content -Path $env:MOABCONFIG_PATH -Value '    edge_makepri_path = "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\$env:WINDOWS_SDK_VERSION\\x64\\makepri.exe"'
      - Add-Content -Path $env:MOABCONFIG_PATH -Value '    edge_makeappx_path = "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\$env:WINDOWS_SDK_VERSION\\x64\\makeappx.exe"'
    #  - Dir "C:\\Program Files (x86)\\Windows Kits\\10\\bin"
  pre_build:
    commands:
      - '& $env:YARN_BIN install --silent'
  build:
    commands:
      # - '& $env:YARN_BIN run lint'
      - '& $env:YARN_BIN run test.unit --verbose=false'
      - '& $env:YARN_BIN run build.prod --silent'
      - '& "$env:CODEBUILD_SRC_DIR_moab\moab-bin.exe" build'

artifacts:
  files:
    - build/**/*
  discard-paths: yes
