version: 0.2

phases:
  install:
    commands:
      - powershell -NoProfile -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      - choco install -y yarn
      - dir C:\ProgramData\Chocolatey
      - node -v
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run lint
      - yarn run test.unit
      - yarn run build.prod
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makeappx.exe"'
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makepri.exe"'
