version: 0.2

phases:
  install:
    commands:
      - echo $Env:CODEBUILD_SRC_DIR_moab
      - echo $CODEBUILD_SRC_DIR_moab
      - powershell -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      # - choco install -y yarn
      - choco install -y googlechrome
      - choco install -y opera
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install --silent
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '[projects]'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '  [projects.ghostery-extension]'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '    edge_makepri_path = "C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64\\makepri.exe"'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '    edge_makeappx_path = "C:\\Program Files (x86)\\Windows Kits\\8.1\\bin\\x64\\makeappx.exe"'
      - type C:\Users\ContainerAdministrator\.moabconfig
  build:
    commands:
      # - yarn run lint
      - yarn run test.unit
      - yarn run build.prod --silent > NUL
      - '& "$env:CODEBUILD_SRC_DIR_moab\moab-bin.exe" makezip'

artifacts:
  files:
    - build/**/*
  discard-paths: yes