version: 0.2

phases:
  install:
    commands:
      - powershell -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      # - choco install -y yarn
      - choco install --confirm --limit-output --no-progress --ignore-checksums googlechrome opera windows-sdk-10.1
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install --silent
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '[projects]'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '  [projects.ghostery-extension]'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '    edge_makepri_path = "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x64\\makepri.exe"'
      - Add-Content -Path C:\Users\ContainerAdministrator\.moabconfig -Value '    edge_makeappx_path = "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x64\\makeappx.exe"'
  build:
    commands:
      # - yarn run lint
      - yarn run test.unit --verbose=false
      - yarn run build.prod --silent
      - '& "$env:CODEBUILD_SRC_DIR_moab\moab-bin.exe" build'

artifacts:
  files:
    - build/**/*
  discard-paths: yes