version: 0.2

phases:
  install:
    commands:
      - echo $Env:CODEBUILD_SRC_DIR_moab
      - echo $CODEBUILD_SRC_DIR_moab
      - dir $Env:CODEBUILD_SRC_DIR_moab
      - dir ${CODEBUILD_SRC_DIR_moab}
      - powershell -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      # - choco install -y yarn
      - dir "C:\Program Files (x86)\"
      - choco install -y googlechrome
      - dir "C:\Program Files (x86)\Google\"
      - choco install -y opera
      - dir "C:\Program Files (x86)\"
      - dir "C:\Program Files\"
      # - $env:Path += ";C:\Program Files (x86)\Yarn\bin\"
      # - echo $env:Path
      # - $Env:PATH += ";C:\Program Files (x86)\Yarn\bin\"
      # - echo $Env:PATH
      # - dir "C:\Program Files (x86)\Yarn\bin\"
      # - '"C:\Program Files (x86)\Yarn\bin\yarn"'
      # - node -v
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install --silent
      - echo "[projects]" >> C:\Users\ContainerAdministrator\.moabconfig
      - echo "  [projects.ghostery-extension]" >> C:\Users\ContainerAdministrator\.moabconfig
      - echo "    edge_makepri_path = """C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makepri.exe"" >> C:\Users\ContainerAdministrator\.moabconfig
      - echo "    edge_makeappx_path = """C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makeappx.exe"" >> C:\Users\ContainerAdministrator\.moabconfig
      - type C:\Users\ContainerAdministrator\.moabconfig
  build:
    commands:
      # - yarn run lint
      - yarn run test.unit
      - yarn run build.prod --silent
      - '& "$env:CODEBUILD_SRC_DIR_moab\moab-bin.exe" makezip'
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makeappx.exe"'
      # - 'dir "C:\Program Files (x86)\Windows Kits\8.1\bin\x64\makepri.exe"'

artifacts:
  files:
    - build/**/*
  discard-paths: yes