version: 0.2

env:
  variables:
    YARN_BIN: 'C:\Program Files (x86)\Yarn\bin\yarn.cmd'
    MOABCONFIG_PATH: 'C:\Users\ContainerAdministrator\.moabconfig'

phases:
  install:
    commands:
    #  - choco install --confirm --limit-output --no-progress --ignore-checksums git nodejs yarn googlechrome opera windows-sdk-10.1
      - choco install --confirm --limit-output --no-progress --ignore-checksums git nodejs yarn opera
      - Add-Content -Path $env:MOABCONFIG_PATH -Value '[projects]'
      - Add-Content -Path $env:MOABCONFIG_PATH -Value '  [projects.ghostery-extension]'
    #  - Add-Content -Path $env:MOABCONFIG_PATH -Value '    edge_makepri_path = "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x64\\makepri.exe"'
    #  - Add-Content -Path $env:MOABCONFIG_PATH -Value '    edge_makeappx_path = "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x64\\makeappx.exe"'
  pre_build:
    commands:
      - '& $env:YARN_BIN install --silent'
  build:
    commands:
      # - '& $env:YARN_BIN run lint'
      - '& $env:YARN_BIN run test.unit --verbose=false'
      - '& $env:YARN_BIN run build.prod --silent'
      - '& "$env:CODEBUILD_SRC_DIR_moab\moab-bin.exe" build'

artifacts:
  files:
    - build/**/*
  discard-paths: yes
